BIN_PATH = /home/zhangdi/bin/bin
AS      = $(BIN_PATH)/arm-none-eabi-as
CC      = $(BIN_PATH)/arm-none-eabi-gcc
LD      = $(BIN_PATH)/arm-none-eabi-ld 
OBJCOPY = $(BIN_PATH)/arm-none-eabi-objcopy 
AR      = $(BIN_PATH)/arm-none-eabi-ar
SRC     =/home/zhangdi/Programs/stm32/src
SIT     =
INC_PATH= $(SRC)/led $(SRC)/sys $(SRC)/delay $(SRC)/oled $(SRC)/usart $(SRC)/iic $(SRC)/usart3 $(SRC)/mpu6050 $(SRC)/key $(SRC)/adc $(SRC)/motor
